---
Rooms:
  - Name: Bed Room
    Appliances:
      - Name: Pump
        Type: GPIO
        Pin: 17
      - Name: Light
        Type: GPIO
        Pin: 27
  - Name: Auto
    Appliances:
      - Name: Auto Pump
        Type: Script
        Status: test -f ${HOME}/WebGPIO/auto_on > /dev/null
        Action:
          On: touch ${HOME}/WebGPIO/auto_on
          Off: rm ${HOME}/WebGPIO/auto_on
  # - Name: Scripts
  #   Appliances:
  #     - Name: Internet
  #       Type: Script
  #       Status: ping -c 1 8.8.8.8 > /dev/null
  #       Timeout: 0.3
  #     - Name: Nginx
  #       Type: Script
  #       Status: sudo systemctl is-active --quiet nginx 2> /dev/null
  #       Action: 
  #         On: sudo systemctl start nginx
  #         Off: sudo systemctl stop nginx


#Settings:
#  Host: 0.0.0.0
#  Port: 8000
#  Debug: True
#  SSL:
#    Enabled: False
#    Path: default
#    Certificate: WebGPIO.cer
#    Key: WebGPIO.key
#  Inverted: False
#  RefreshRate: 4